[build]
  command = "npm run build"
	publish = "dist"

[build.environment]
  REACT_APP_API_BASE = "https://api.178-105-133-94.sslip.io"
  REACT_APP_NODE_URL = "https://api.178-105-133-94.sslip.io"
  REACT_APP_WALLET_BASE = "https://wallet.178-105-133-94.sslip.io"
  REACT_APP_WALLET_URL = "https://wallet.178-105-133-94.sslip.io"
  REACT_APP_DEX_REGISTRY_API = "https://dex-api.178-105-133-94.sslip.io"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
