[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_CHAIN_BASE = "http://178.105.133.94:6500"
  REACT_APP_API_BASE = "http://178.105.133.94:9000"
  REACT_APP_WALLET_BASE = "http://178.105.133.94:8080"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
